### PR TITLE
allennlp not required

### PR DESCRIPTION
**Pull request by KoichiYasuoka**

### CODE REVIEW

**Comment by KoichiYasuoka** [comment]
And we need to move `camphr_allennlp.common.util` and other modules from original ones.

**Comment by KoichiYasuoka** [comment]
I left `elmo.py` unchanged. Now [unofficial-udify](https://github.com/tamuhey/udify) can use `camphr_allennlp`.

**Comment by KoichiYasuoka** [comment]
@tamuhey san, I've wrote my motivation for this PR in [my diary](https://srad.jp/~yasuoka/journal/645312/) (written in Japanese). If you have time, please read it.

**Comment by tamuhey** [comment]
@KoichiYasuoka Thank you for your PR, and I really appreciate your effort!
However, we do not have enough resources to fully maintain this allennlp verndoring.
I think it is better to publish your patched allennlp (https://github.com/allenai/allennlp/pull/4976) to  PyPI as an alias, and make `camphr_allennlp` to depend on it.
Actually, we used to publish a fork of `allennlp` as [unofficial-allennlp-nightly](https://github.com/allenai/allennlp/pull/4976) and `camphr` used it.

**Comment by KoichiYasuoka** [comment]
Thank you @tamuhey san, I will seek another way...

**Pull request closed without merging**
